### ISSUE TITLE
Zeep always overriding namespace prefixes defined in the WSDL?

### ISSUE THREAD

**Issue by plaes** [mvantellingen/python-zeep#870]
For example in my WSDL ( https://www.emta.ee/sites/default/files/ariklient/aktsiisid-vara-hasartmang/hampi/hampi-xrd-v6.wsdl ) I have following namespace definitions:
```
<wsdl:definitions
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://emta-v6.x-road.eu"
  xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
  name="ompi"
  targetNamespace="http://emta-v6.x-road.eu">
```

```
python -m zeep wsdl/hampi-xrd-v4.wsdl

Prefixes:
     xsd: http://www.w3.org/2001/XMLSchema
     ns0: http://emta-v6.x-road.eu
     ns1: http://x-road.eu/xsd/xroad.xsd
     ns2: http://www.w3.org/XML/1998/namespace
     ns3: http://x-road.eu/xsd/identifiers
```

Is there a possibility zeep does not override the prefixes and I could use `xrd:XRoadClientIdentifierType` instead of `ns3:XRoadClientIdentifierType` ?
